<style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      max-height: 500px !important;
      margin: auto;
  }
  </style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
<?php $i=0;?>
<?php foreach( $items AS $item):?>
<li data-target="#myCarousel" data-slide-to="<?php echo $i;?>" class="<?php if ($i==0) echo 'active';?>"></li>
<?php endforeach;?>      
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
<?php $n=0;?>
<?php foreach($items AS $item):?>
    <div class="item<?php if ($n==0) {echo ' active'; $n++;}?>" >
      <img class="athen-round-image" src="/productImage/<?php echo $item["imagepath"]?>" alt="">
      <!-- Product Description Panel-->
        <div class="carousel-caption carousel-caption-athen">
          <h3><?php echo $item["title"];?> 
          <?php if ($item["price"]):?>
          <span class="price">$<?php echo $item["price"];?></span>
          <?php endif;?>
          </h3>
          <?php echo $item["description"];?>
        </div>
      <!-- End of Product Panel -->
    </div>
<?php endforeach;?>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
