<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
<h1>雅典集</h1>
<p>竹北市勝利五路111號
<br/>TEL: 03-6576887
</p>
<div class="well">
 <p>雅典集的網站還在施工中<br/>
 請先參觀老闆娘的 FaceBook</p>
 <button type="button" class="btn btn-sm btn-info"
    onclick="window.location.href='https://www.facebook.com/groups/1487334338148298'"
 >雅典集韓國館～一起遊首爾</button>
 <br/>
 <br/>
 <button type="button" class="btn btn-sm btn-info"
    onclick="window.location.href='https://www.facebook.com/groups/550797318413974'"
 >雅請進！雅典集廚房</button>
 
</div>

</div>

