<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
<div class="row">
<div class="col-sm-6">
    <img src="images/logo_300.png">
</div>
<div class="col-sm-6">
<h1>雅典集</h1>
<h3>竹北市勝利五路111號
    <br/>TEL: 03-6576887</h3>
</div>

</div><!-- end row -->
<div class="well">
 <p>雅典集在 2008 年成立于竹北市的高級住宅區。
專營正版韓國，日本，香港制造的女裝，童裝， 精品，配件。
深受附近鄰居及世界各地客人喜愛。</p>
<p><b>熱情溫馨的美麗老闆娘</b>是日韓港旅遊達人，專精精品、飾品、女裝、童裝代購。</p>
<p/><b>優雅時尚的採購女助手</b>則對流行服裝穿搭獨樹一格，專精日韓，女裝，女鞋，精品，皮件等等。</p>
<p/><b>氣質女店長</b>深知客人需求，符合客人預算，為大家推薦最時尚最新款的穿搭。</p>
<p>請參觀老闆娘的 FaceBook</p>
 <button 
    type="button" 
    class="btn btn-sm btn-info"
    onclick="window.location.href='https://www.facebook.com/groups/1487334338148298'"
 >雅典集～美國我來了6/1-6/10</button>
 <br/><br/>
 <button 
    type="button" 
    class="btn btn-sm btn-info"
    onclick="window.location.href='https://www.facebook.com/groups/550797318413974'"
 >請進！雅典集廚房</button>
 
</div>
</div>

