    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">雅典集</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <!--<li class="active"><a href="#">首頁</a></li>
            <li><a href="#about">關於</a></li>
            <!--<li><a href="#contact">聯絡</a></li>-->
            
            
          
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">韓國 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">女裝</a></li>
                <li><a href="#">女鞋</a></li>
                <li><a href="#">童裝</a></li>
                <li><a href="#">彩妝</a></li>
                <li><a href="#">食品</a></li>
              </ul>
              
              
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">日本 <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">食品</a></li>
                <li><a href="#">生活用品</a></li>
                <li><a href="#">服裝</a></li>
                <li><a href="#">赤ちゃん</a></li>
                <li><a href="#">LC 鍋</a></li>
                <li><a href="#">Disney</a></li>
              </ul>
            </li>  
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">香港<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">食品</a></li>
                <li><a href="#">生活用品</a></li>
                <li><a href="#">服裝</a></li>
                <li><a href="#">Disney</a></li>
              </ul>
            </li>  
            
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">廚房<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">鍋具</a></li>
                <li><a href="#">廚具</a></li>
                <li><a href="#">食品</a></li>
                <li><a href="#">生鮮</a></li>
              </ul>
            </li> <!-- 
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">美國<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">準備中</li>
              </ul>
            </li>    -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
