<form method="POST" action="saveProducts.php" enctype="multipart/form-data">
    
    <input type="hidden" name="cat" value = "<?php echo $categoryId;?>">
    <input type="hidden" name="subCat" value="<?php echo $subCategoryId;?>">
    <input type="hidden" name="action" value="new">
<div class="row  athen-solid-border">
<button type="submit" class="btn-btn-sm btn-info">新增產品</button>  
<div class="col-md-3 ">
    照片 <input type="file" name="image"></input>
    
  </div>
  <div class="col-md-2">
    產品名稱<br/>
    <input type="text" name="title"></input>
  </div>
  <div class="col-md-4">
    產品敘述<br/>
    <input type="text" name="description"></input>
  </div>
  <div class="col-md-1">
    價錢<br/>
    $ <input type="text" name="price"></input>
  </div>
</div>
</form>
