<!DOCTYPE html>
<html lang="en">
<?php include( "views/head.phtml");?>
<head>
    <script type="text/javascript" src="editor.js"></script>
</head>
<body role="document">
<?php include( "views/navbar.phtml");?>
<div class='well'>
<?php $buttonName="更新產品";
//$categoryId = $data["categoryId"];
//$subCategoryId = $data["subCategoryId"];
//var_dump($data);
$action = "update";
$categoryId = $data["category"];
$subCategoryId = $data["subcategory"];
?>
<?php include( "views/oneProductForm.phtml" );?>
<?php include( "views/bootstrapjs.phtml");?>
</div><!-- end of div well-->
</html>
