<!DOCTYPE html>
<html lang="en">
<?php include( "views/head.phtml");?>
<head>
    <script type="text/javascript" src="editor.js"></script>
</head>
<body role="document">
<?php include( "views/navbar.phtml");?>
<div class="container theme-showcase" role="main">
    
<div>
    <h1>產品管理 <?php echo $category;?> -> <?php echo $subCategory;?></h1>
</div>
<?php include(__DIR__."/addNewProduct.phtml");?>
<?php if( $results ===false):?>
此項目現在沒有產品
<?php else:?>
<?php //var_dump($results);?>
<!--
<div class="row  athen-solid-border">
  <div class="col-md-3 ">
    Image
  </div>
  <div class="col-md-1">
   ID
  </div>
  <div class="col-md-2">
    Title
  </div>
  <div class="col-md-4">
    Des
  </div>
  <div class="col-md-1">
   price
  </div>
</div>-->


<?php foreach ($results AS $r):?>

<div class="row athen-solid-border athen-solid-border">
  <button 
    type="button" 
    class="btn btn-sm btn-primary"
    onclick="alert('edit');"
 >編輯</button>  
  <button 
    type="button" 
    class="btn btn-sm btn-danger"
    onclick="deleteProduct('<?php echo $r["id"]?>');"
 >刪除</button>
  <div class="col-md-3">
    <img class="athen-product-img-edit" src="/productImage/<?php echo $r["imagepath"];?>">
  </div>
  <div class="col-md-1">
   <b>編號：</b><?php echo $r["id"];?>
  </div>
  <div class="col-md-2">
    <b>標題：</b><?php echo $r["title"];?>
  </div>
  <div class="col-md-4">
    <b>敘述：</b><?php echo $r["description"];?>
  </div>
  <div class="col-md-1">
    <b>價錢：</b><?php echo $r["price"];?>
  </div>
</div>
<?php endforeach;?>
<?php endif;?>

<?php include( "views/bootstrapjs.phtml");?>
</div><!-- /container -->
</body>
</html>





