<?php
include(__DIR__."/../../config/category.php");
?>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.php">雅典集</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
<?php foreach ($_category_relation AS $key=>$subCats ):?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $_category[$key]?> <span class="caret"></span></a>
              <ul class="dropdown-menu">
<?php foreach ($subCats AS $subCat):?>
                <li><a href="manageProducts.php?cat=<?php echo $key;?>&subCat=<?php echo $subCat;?>"><?php echo $_subCategory[$subCat]?></a></li>  
<?php endforeach;?>
              </ul>
            </li>
<?php endforeach;?>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
<br/><br/><br/>
